# Site settings
title: Raphy Varghese
email: raphy202@gmail.com
description: "Personal Weblog"
baseurl: "/imagina"
url: "https://vargheseraphy.github.io"
twitter_username: "vargheseraphy"
github_username:  "vargheseraphy"

# Build settings
markdown:  kramdown
permalink: "/:year/:month/:title"
paginate:  20
plugins:
  - jekyll-paginate
